const text={
  about:{
    title:'About',
    paragraph:[
      'When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. ',

      'When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin'
    ],
  },
  stories:{
    title:'Stories',
    paragraph:[
      'When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. ',

      'When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin'
    ],
  },
  news:{
    title:'News',
    paragraph:[
      'When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. ',

      'When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. When seeking legal advice it’s important to talk to a qualified solicitor who has the expertise to help you. The Law Society website lists solicitors who hold a current practising certificate and professional indemnity insurance in Ireland and updates these details daily. You can search for a solicitor firm or an individual solicitor by name or by location. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin. As at 14 August 2018, there were 6687 solicitors and 952 legal firms in County Dublin'
    ],
  }
}

export default text
